import 'package:flutter/material.dart';
import '../models/kana_model.dart';

const kanaInfo = const [
  KanaDict(
      id: 'kd1',
      kanarow: 'preARow',
      category: 'Hiragana Flashcard',
      kana: 'あ',
      roomaji: 'a',
      color: Colors.green),
  KanaDict(
      id: 'kd2',
      kanarow: 'preARow',
      category: 'Hiragana Flashcard',
      kana: 'い',
      roomaji: 'i',
      color: Colors.green),
  KanaDict(
      id: 'kd3',
      kanarow: 'preARow',
      category: 'Hiragana Flashcard',
      kana: 'う',
      roomaji: 'u',
      color: Colors.green),
  KanaDict(
      id: 'kd4',
      kanarow: 'preARow',
      category: 'Hiragana Flashcard',
      kana: 'え',
      roomaji: 'e',
      color: Colors.green),
  KanaDict(
      id: 'kd5',
      kanarow: 'preARow',
      category: 'Hiragana Flashcard',
      kana: 'お',
      roomaji: 'o',
      color: Colors.green),
  KanaDict(
      id: 'kd6',
      kanarow: 'kaRow',
      category: 'Hiragana Flashcard',
      kana: 'か',
      roomaji: 'ka',
      color: Colors.blue),
  KanaDict(
      id: 'kd7',
      kanarow: 'kaRow',
      category: 'Hiragana Flashcard',
      kana: 'き',
      roomaji: 'ki',
      color: Colors.blue),
  KanaDict(
      id: 'kd8',
      kanarow: 'kaRow',
      category: 'Hiragana Flashcard',
      kana: 'く',
      roomaji: 'ku',
      color: Colors.blue),
  KanaDict(
      id: 'kd9',
      kanarow: 'kaRow',
      category: 'Hiragana Flashcard',
      kana: 'け',
      roomaji: 'ke',
      color: Colors.blue),
  KanaDict(
      id: 'kd10',
      kanarow: 'kaRow',
      category: 'Hiragana Flashcard',
      kana: 'こ',
      roomaji: 'ko',
      color: Colors.blue),
  KanaDict(
      id: 'kd11',
      kanarow: 'saRow',
      category: 'Hiragana Flashcard',
      kana: 'さ',
      roomaji: 'sa',
      color: Colors.purple),
  KanaDict(
      id: 'kd12',
      kanarow: 'saRow',
      category: 'Hiragana Flashcard',
      kana: 'し',
      roomaji: 'shi',
      color: Colors.purple),
  KanaDict(
      id: 'kd13',
      kanarow: 'saRow',
      category: 'Hiragana Flashcard',
      kana: 'す',
      roomaji: 'su',
      color: Colors.purple),
  KanaDict(
      id: 'kd14',
      kanarow: 'saRow',
      category: 'Hiragana Flashcard',
      kana: 'せ',
      roomaji: 'se',
      color: Colors.purple),
  KanaDict(
      id: 'kd15',
      kanarow: 'saRow',
      category: 'Hiragana Flashcard',
      kana: 'そ',
      roomaji: 'so',
      color: Colors.purple),
  KanaDict(
      id: 'kd16',
      kanarow: 'taRow',
      category: 'Hiragana Flashcard',
      kana: 'た',
      roomaji: 'ta',
      color: Colors.teal),
  KanaDict(
      id: 'kd17',
      kanarow: 'taRow',
      category: 'Hiragana Flashcard',
      kana: 'ち',
      roomaji: 'chi',
      color: Colors.teal),
  KanaDict(
      id: 'kd18',
      kanarow: 'taRow',
      category: 'Hiragana Flashcard',
      kana: 'つ',
      roomaji: 'tsu',
      color: Colors.teal),
  KanaDict(
      id: 'kd19',
      kanarow: 'taRow',
      category: 'Hiragana Flashcard',
      kana: 'て',
      roomaji: 'te',
      color: Colors.teal),
  KanaDict(
      id: 'kd20',
      kanarow: 'taRow',
      category: 'Hiragana Flashcard',
      kana: 'と',
      roomaji: 'to',
      color: Colors.teal),
  KanaDict(
      id: 'kd21',
      kanarow: 'naRow',
      category: 'Hiragana Flashcard',
      kana: 'な',
      roomaji: 'na',
      color: Colors.orange),
  KanaDict(
      id: 'kd22',
      kanarow: 'naRow',
      category: 'Hiragana Flashcard',
      kana: 'に',
      roomaji: 'ni',
      color: Colors.orange),
  KanaDict(
      id: 'kd23',
      kanarow: 'naRow',
      category: 'Hiragana Flashcard',
      kana: 'ぬ',
      roomaji: 'nu',
      color: Colors.orange),
  KanaDict(
      id: 'kd24',
      kanarow: 'naRow',
      category: 'Hiragana Flashcard',
      kana: 'ね',
      roomaji: 'ne',
      color: Colors.orange),
  KanaDict(
      id: 'kd25',
      kanarow: 'naRow',
      category: 'Hiragana Flashcard',
      kana: 'の',
      roomaji: 'no',
      color: Colors.orange),
  KanaDict(
      id: 'kd26',
      kanarow: 'haRow',
      category: 'Hiragana Flashcard',
      kana: 'は',
      roomaji: 'ha',
      color: Colors.blueGrey),
  KanaDict(
      id: 'kd27',
      kanarow: 'haRow',
      category: 'Hiragana Flashcard',
      kana: 'ひ',
      roomaji: 'hi',
      color: Colors.blueGrey),
  KanaDict(
      id: 'kd28',
      kanarow: 'haRow',
      category: 'Hiragana Flashcard',
      kana: 'ふ',
      roomaji: 'fu',
      color: Colors.blueGrey),
  KanaDict(
      id: 'kd29',
      kanarow: 'haRow',
      category: 'Hiragana Flashcard',
      kana: 'へ',
      roomaji: 'he',
      color: Colors.blueGrey),
  KanaDict(
      id: 'kd30',
      kanarow: 'haRow',
      category: 'Hiragana Flashcard',
      kana: 'ほ',
      roomaji: 'ho',
      color: Colors.blueGrey),
  KanaDict(
      id: 'kd31',
      kanarow: 'maRow',
      category: 'Hiragana Flashcard',
      kana: 'ま',
      roomaji: 'ma',
      color: Colors.redAccent),
  KanaDict(
      id: 'kd32',
      kanarow: 'maRow',
      category: 'Hiragana Flashcard',
      kana: 'み',
      roomaji: 'mi',
      color: Colors.redAccent),
  KanaDict(
      id: 'kd33',
      kanarow: 'maRow',
      category: 'Hiragana Flashcard',
      kana: 'む',
      roomaji: 'mu',
      color: Colors.redAccent),
  KanaDict(
      id: 'kd34',
      kanarow: 'maRow',
      category: 'Hiragana Flashcard',
      kana: 'め',
      roomaji: 'me',
      color: Colors.redAccent),
  KanaDict(
      id: 'kd35',
      kanarow: 'maRow',
      category: 'Hiragana Flashcard',
      kana: 'も',
      roomaji: 'mo',
      color: Colors.redAccent),
  KanaDict(
      id: 'kd36',
      kanarow: 'yaRow',
      category: 'Hiragana Flashcard',
      kana: 'や',
      roomaji: 'ya',
      color: Colors.blueAccent),
  KanaDict(
      id: 'kd37',
      kanarow: 'yaRow',
      category: 'Hiragana Flashcard',
      kana: ' ',
      roomaji: ' ',
      color: Colors.white),
  KanaDict(
      id: 'kd38',
      kanarow: 'yaRow',
      category: 'Hiragana Flashcard',
      kana: 'ゆ',
      roomaji: 'yu',
      color: Colors.blueAccent),
  KanaDict(
      id: 'kd39',
      kanarow: 'yaRow',
      category: 'Hiragana Flashcard',
      kana: ' ',
      roomaji: ' ',
      color: Colors.white),
  KanaDict(
      id: 'kd40',
      kanarow: 'yaRow',
      category: 'Hiragana Flashcard',
      kana: 'よ',
      roomaji: 'yo',
      color: Colors.blueAccent),
  KanaDict(
      id: 'kd41',
      kanarow: 'raRow',
      category: 'Hiragana Flashcard',
      kana: 'ら',
      roomaji: 'ra',
      color: Colors.deepPurple),
  KanaDict(
      id: 'kd42',
      kanarow: 'raRow',
      category: 'Hiragana Flashcard',
      kana: 'り',
      roomaji: 'ri',
      color: Colors.deepPurple),
  KanaDict(
      id: 'kd43',
      kanarow: 'raRow',
      category: 'Hiragana Flashcard',
      kana: 'る',
      roomaji: 'ru',
      color: Colors.deepPurple),
  KanaDict(
      id: 'kd44',
      kanarow: 'raRow',
      category: 'Hiragana Flashcard',
      kana: 'れ',
      roomaji: 're',
      color: Colors.deepPurple),
  KanaDict(
      id: 'kd45',
      kanarow: 'raRow',
      category: 'Hiragana Flashcard',
      kana: 'ろ',
      roomaji: 'ro',
      color: Colors.deepPurple),
  KanaDict(
      id: 'kd46',
      kanarow: 'waRow',
      category: 'Hiragana Flashcard',
      kana: 'わ',
      roomaji: 'wa',
      color: Colors.pink),
  KanaDict(
      id: 'kd47',
      kanarow: 'waRow',
      category: 'Hiragana Flashcard',
      kana: ' ',
      roomaji: ' ',
      color: Colors.pink),
  KanaDict(
      id: 'kd48',
      kanarow: 'waRow',
      category: 'Hiragana Flashcard',
      kana: 'を',
      roomaji: 'o',
      color: Colors.pink),
  KanaDict(
      id: 'kd49',
      kanarow: 'waRow',
      category: 'Hiragana Flashcard',
      kana: ' ',
      roomaji: ' ',
      color: Colors.pink),
  KanaDict(
      id: 'kd49',
      kanarow: 'waRow',
      category: 'Hiragana Flashcard',
      kana: 'ん',
      roomaji: 'n',
      color: Colors.pink),

  /* ---Katakana Start--- */

  KanaDict(
      id: 'kd1',
      kanarow: 'preARow',
      category: 'Katakana Flashcard',
      kana: 'ア',
      roomaji: 'a',
      color: Colors.green),
  KanaDict(
      id: 'kd2',
      kanarow: 'preARow',
      category: 'Katakana Flashcard',
      kana: 'イ',
      roomaji: 'i',
      color: Colors.green),
  KanaDict(
      id: 'kd3',
      kanarow: 'preARow',
      category: 'Katakana Flashcard',
      kana: 'ウ',
      roomaji: 'u',
      color: Colors.green),
  KanaDict(
      id: 'kd4',
      kanarow: 'preARow',
      category: 'Katakana Flashcard',
      kana: 'エ',
      roomaji: 'e',
      color: Colors.green),
  KanaDict(
      id: 'kd5',
      kanarow: 'preARow',
      category: 'Katakana Flashcard',
      kana: 'オ',
      roomaji: 'o',
      color: Colors.green),
  KanaDict(
      id: 'kd6',
      kanarow: 'kaRow',
      category: 'Katakana Flashcard',
      kana: 'カ',
      roomaji: 'ka',
      color: Colors.blue),
  KanaDict(
      id: 'kd7',
      kanarow: 'kaRow',
      category: 'Katakana Flashcard',
      kana: 'キ',
      roomaji: 'ki',
      color: Colors.blue),
  KanaDict(
      id: 'kd8',
      kanarow: 'kaRow',
      category: 'Katakana Flashcard',
      kana: 'ク',
      roomaji: 'ku',
      color: Colors.blue),
  KanaDict(
      id: 'kd9',
      kanarow: 'kaRow',
      category: 'Katakana Flashcard',
      kana: 'ケ',
      roomaji: 'ke',
      color: Colors.blue),
  KanaDict(
      id: 'kd10',
      category: 'Katakana Flashcard',
      kanarow: 'kaRow',
      kana: 'コ',
      roomaji: 'ko',
      color: Colors.blue),
  KanaDict(
      id: 'kd11',
      kanarow: 'saRow',
      category: 'Katakana Flashcard',
      kana: 'サ',
      roomaji: 'sa',
      color: Colors.purple),
  KanaDict(
      id: 'kd12',
      kanarow: 'saRow',
      category: 'Katakana Flashcard',
      kana: 'シ',
      roomaji: 'shi',
      color: Colors.purple),
  KanaDict(
      id: 'kd13',
      kanarow: 'saRow',
      category: 'Katakana Flashcard',
      kana: 'ス',
      roomaji: 'su',
      color: Colors.purple),
  KanaDict(
      id: 'kd14',
      kanarow: 'saRow',
      category: 'Katakana Flashcard',
      kana: 'セ',
      roomaji: 'se',
      color: Colors.purple),
  KanaDict(
      id: 'kd15',
      kanarow: 'saRow',
      category: 'Katakana Flashcard',
      kana: 'ソ',
      roomaji: 'so',
      color: Colors.purple),
  KanaDict(
      id: 'kd16',
      kanarow: 'taRow',
      category: 'Katakana Flashcard',
      kana: 'タ',
      roomaji: 'ta',
      color: Colors.teal),
  KanaDict(
      id: 'kd17',
      kanarow: 'taRow',
      category: 'Katakana Flashcard',
      kana: 'チ',
      roomaji: 'chi',
      color: Colors.teal),
  KanaDict(
      id: 'kd18',
      kanarow: 'taRow',
      category: 'Katakana Flashcard',
      kana: 'ツ',
      roomaji: 'tsu',
      color: Colors.teal),
  KanaDict(
      id: 'kd19',
      kanarow: 'taRow',
      category: 'Katakana Flashcard',
      kana: 'テ',
      roomaji: 'te',
      color: Colors.teal),
  KanaDict(
      id: 'kd20',
      kanarow: 'taRow',
      category: 'Katakana Flashcard',
      kana: 'ト',
      roomaji: 'to',
      color: Colors.teal),
  KanaDict(
      id: 'kd21',
      kanarow: 'naRow',
      category: 'Katakana Flashcard',
      kana: 'ナ',
      roomaji: 'na',
      color: Colors.orange),
  KanaDict(
      id: 'kd22',
      kanarow: 'naRow',
      category: 'Katakana Flashcard',
      kana: 'ニ',
      roomaji: 'ni',
      color: Colors.orange),
  KanaDict(
      id: 'kd23',
      kanarow: 'naRow',
      category: 'Katakana Flashcard',
      kana: 'ヌ',
      roomaji: 'nu',
      color: Colors.orange),
  KanaDict(
      id: 'kd24',
      kanarow: 'naRow',
      category: 'Katakana Flashcard',
      kana: 'ネ',
      roomaji: 'ne',
      color: Colors.orange),
  KanaDict(
      id: 'kd25',
      kanarow: 'naRow',
      category: 'Katakana Flashcard',
      kana: 'ノ',
      roomaji: 'no',
      color: Colors.orange),
  KanaDict(
      id: 'kd26',
      kanarow: 'haRow',
      category: 'Katakana Flashcard',
      kana: 'ハ',
      roomaji: 'ha',
      color: Colors.blueGrey),
  KanaDict(
      id: 'kd27',
      kanarow: 'haRow',
      category: 'Katakana Flashcard',
      kana: 'ヒ',
      roomaji: 'hi',
      color: Colors.blueGrey),
  KanaDict(
      id: 'kd28',
      kanarow: 'haRow',
      category: 'Katakana Flashcard',
      kana: 'フ',
      roomaji: 'fu',
      color: Colors.blueGrey),
  KanaDict(
      id: 'kd29',
      kanarow: 'haRow',
      category: 'Katakana Flashcard',
      kana: 'へ',
      roomaji: 'he',
      color: Colors.blueGrey),
  KanaDict(
      id: 'kd30',
      kanarow: 'haRow',
      category: 'Katakana Flashcard',
      kana: 'ホ',
      roomaji: 'ho',
      color: Colors.blueGrey),
  KanaDict(
      id: 'kd31',
      kanarow: 'maRow',
      category: 'Katakana Flashcard',
      kana: 'マ',
      roomaji: 'ma',
      color: Colors.redAccent),
  KanaDict(
      id: 'kd32',
      kanarow: 'maRow',
      category: 'Katakana Flashcard',
      kana: 'ミ',
      roomaji: 'mi',
      color: Colors.redAccent),
  KanaDict(
      id: 'kd33',
      kanarow: 'maRow',
      category: 'Katakana Flashcard',
      kana: 'ム',
      roomaji: 'mu',
      color: Colors.redAccent),
  KanaDict(
      id: 'kd34',
      kanarow: 'maRow',
      category: 'Katakana Flashcard',
      kana: 'メ',
      roomaji: 'me',
      color: Colors.redAccent),
  KanaDict(
      id: 'kd35',
      kanarow: 'maRow',
      category: 'Katakana Flashcard',
      kana: 'モ',
      roomaji: 'mo',
      color: Colors.redAccent),
  KanaDict(
      id: 'kd36',
      kanarow: 'yaRow',
      category: 'Katakana Flashcard',
      kana: 'ヤ',
      roomaji: 'ya',
      color: Colors.blueAccent),
  KanaDict(
      id: 'kd37',
      kanarow: 'yaRow',
      category: 'Katakana Flashcard',
      kana: ' ',
      roomaji: ' ',
      color: Colors.white),
  KanaDict(
      id: 'kd38',
      kanarow: 'yaRow',
      category: 'Katakana Flashcard',
      kana: 'ユ',
      roomaji: 'yu',
      color: Colors.blueAccent),
  KanaDict(
      id: 'kd39',
      kanarow: 'yaRow',
      category: 'Katakana Flashcard',
      kana: ' ',
      roomaji: ' ',
      color: Colors.white),
  KanaDict(
      id: 'kd40',
      kanarow: 'yaRow',
      category: 'Katakana Flashcard',
      kana: 'ヨ',
      roomaji: 'yo',
      color: Colors.blueAccent),
  KanaDict(
      id: 'kd41',
      kanarow: 'raRow',
      category: 'Katakana Flashcard',
      kana: 'ラ',
      roomaji: 'ra',
      color: Colors.deepPurple),
  KanaDict(
      id: 'kd42',
      kanarow: 'raRow',
      category: 'Katakana Flashcard',
      kana: 'リ',
      roomaji: 'ri',
      color: Colors.deepPurple),
  KanaDict(
      id: 'kd43',
      kanarow: 'raRow',
      category: 'Katakana Flashcard',
      kana: 'ル',
      roomaji: 'ru',
      color: Colors.deepPurple),
  KanaDict(
      id: 'kd44',
      kanarow: 'raRow',
      category: 'Katakana Flashcard',
      kana: 'レ',
      roomaji: 're',
      color: Colors.deepPurple),
  KanaDict(
      id: 'kd45',
      kanarow: 'raRow',
      category: 'Katakana Flashcard',
      kana: 'ロ',
      roomaji: 'ro',
      color: Colors.deepPurple),
  KanaDict(
      id: 'kd46',
      kanarow: 'waRow',
      category: 'Katakana Flashcard',
      kana: 'ワ',
      roomaji: 'wa',
      color: Colors.pink),
  KanaDict(
      id: 'kd47',
      kanarow: 'waRow',
      category: 'Katakana Flashcard',
      kana: ' ',
      roomaji: ' ',
      color: Colors.pink),
  KanaDict(
      id: 'kd48',
      kanarow: 'waRow',
      category: 'Katakana Flashcard',
      kana: 'ヲ',
      roomaji: 'o',
      color: Colors.pink),
  KanaDict(
      id: 'kd49',
      kanarow: 'waRow',
      category: 'Katakana Flashcard',
      kana: ' ',
      roomaji: ' ',
      color: Colors.pink),
  KanaDict(
      id: 'kd49',
      kanarow: 'waRow',
      category: 'Katakana Flashcard',
      kana: 'ン',
      roomaji: 'n',
      color: Colors.pink),
];
