final katakanaQuestions = [
  {
    "id": "kata_13",
    "memo": "Foods",
    "question": "images/foods/mayonnaise.png",
    "answers": [
      {"text": "マーヨネズ", 'score': 0},
      {"text": "マヨネーズ", 'score': 1},
      {"text": "マヨーネズ", 'score': 0},
    ],
    "meaning": "mayonnaise",
  },
  {
    "id": "kata_12",
    "memo": "Foods",
    "question": "images/foods/ramen.png",
    "answers": [
      {"text": "ラーメーン", 'score': 0},
      {"text": "ラメーン", 'score': 0},
      {"text": "ラーメン", 'score': 1},
    ],
    "meaning": "ramen",
  },
  {
    "id": "kata_11",
    "memo": "Foods",
    "question": "images/foods/hamburger.png",
    "answers": [
      {"text": "ハーンバガー", 'score': 0},
      {"text": "ハンバガー", 'score': 0},
      {"text": "ハンバーガー", 'score': 1},
    ],
    "answer": "ハンバーガー",
    "meaning": "hanburger",
  },
  {
    "id": "kata_10",
    "memo": "Foods",
    "question": "images/foods/orange.png",
    "answers": [
      {"text": "オレンジ", 'score': 1},
      {"text": "オランジ", 'score': 0},
      {"text": "オレソツ", 'score': 0},
    ],
    "answer": "オレンジ",
    "meaning": "orange",
  },
  {
    "id": "kata_9",
    "memo": "Foods",
    "question": "images/foods/cheese.png",
    "answers": [
      {"text": "チース", 'score': 0},
      {"text": "チス", 'score': 0},
      {"text": "チーズ", 'score': 1},
    ],
    "answer": "チーズ",
    "meaning": "cheese",
  },
  {
    "id": "kata_8",
    "memo": "Foods",
    "question": "images/foods/curry.png",
    "answers": [
      {"text": "カレー", 'score': 1},
      {"text": "カーレ", 'score': 0},
      {"text": "カーレー", 'score': 0},
    ],
    "answer": "カレー",
    "meaning": "curry",
  },
  {
    "id": "kata_7",
    "memo": "Foods",
    "question": "images/foods/melon.png",
    "answers": [
      {"text": "メロン", 'score': 1},
      {"text": "メーロン", 'score': 0},
      {"text": "メロソ", 'score': 0},
    ],
    "answer": "メロン",
    "meaning": "melon",
  },
  {
    "id": "kata_6",
    "memo": "Foods",
    "question": "images/foods/pepper.png",
    "answers": [
      {"text": "ピマーン", 'score': 0},
      {"text": "ピマーソ", 'score': 0},
      {"text": "ピーマン", 'score': 1},
    ],
    "answer": "ピーマン",
    "meaning": "pepper",
  },
  {
    "id": "kata_5",
    "memo": "Foods",
    "question": "images/foods/pineapple.png",
    "answers": [
      {"text": "パナップル", 'score': 0},
      {"text": "パイナップル", 'score': 1},
      {"text": "パイナプル", 'score': 0},
    ],
    "answer": "パイナップル",
    "meaning": "pineapple",
  },
  {
    "id": "kata_4",
    "memo": "Foods",
    "question": "images/foods/beef.png",
    "answers": [
      {"text": "ヒーフ", 'score': 0},
      {"text": "ビーフ", 'score': 1},
      {"text": "ビフ", 'score': 0},
    ],
    "answer": "ビーフ",
    "meaning": "beef",
  },

//   {
//     "id": "kata_3",
//     "memo": "Foods",
//     "question": "images/foods/pizza.png",
//     "choices_a": "ピッザ",
//     "choices_b": "ピッザー",
//     "choices_c": "ピーザ",
//     "choices_d": "ピザ",
//     "answer": "ピザ",
//     "meaning": "pizza",
//   },
//   {
//     "id": "kata_2",
//     "memo": "Foods",
//     "question": "images/foods/banana.png",
//     "choices_a": "ハナナ",
//     "choices_b": "バナナ",
//     "choices_c": "パヌヌ",
//     "choices_d": "バヌヌ",
//     "answer": "バナナ",
//     "meaning": "banana",
//   },
//   {
//     "id": "kata_1",
//     "memo": "Foods",
//     "question": "images/foods/croquette.png",
//     "choices_a": "コッロケ",
//     "choices_b": "コロッケ",
//     "choices_c": "コロケ",
//     "choices_d": "コッロッケ",
//     "answer": "コッロケ",
//     "meaning": "croquette",
//   },
//   {
//     "id": "id",
//     "memo": "memo",
//     "question": "question",
//     "choices_a": "choicesA",
//     "choices_b": "choicesB",
//     "choices_c": "choicesC",
//     "choices_d": "choicesD",
//     "answer": "answer",
//     "meaning": "meaning",
//   },
  {
    "id": "acc1",
    "memo": "Fashion",
    "question": "images/fashion/bag.png",
    "answers": [
      {"text": "バグ", 'score': 0},
      {"text": "バッグ", 'score': 1},
      {"text": "バク", 'score': 0},
    ],
    "answer": "バッグ",
    "meaning": "bag",
  },
  {
    "id": "acc2",
    "memo": "Fashion",
    "question": "images/fashion/longsleeve.png",
    "answers": [
      {"text": "Ｙシャツ", 'score': 1},
      {"text": "Ｙショツ", 'score': 0},
      {"text": "Ｙツャシ", 'score': 0},
    ],
    "answer": "Ｙシャツ",
    "meaning": "longsleeve",
  },
  {
    "id": "acc3",
    "memo": "Fashion",
    "question": "images/fashion/skirt.png",
    "answers": [
      {"text": "スかート", 'score': 0},
      {"text": "スカット", 'score': 0},
      {"text": "スカート", 'score': 1},
    ],
    "answer": "スカート",
    "meaning": "skirt",
  },
  {
    "id": "acc4",
    "memo": "Fashion",
    "question": "images/fashion/necktie.png",
    "answers": [
      {"text": "ネクッタイ", 'score': 0},
      {"text": "ネックタイ", 'score': 0},
      {"text": "ネクタイ", 'score': 1},
    ],
    "answer": "ネクタイ",
    "meaning": "necktie",
  },
  {
    "id": "acc5",
    "memo": "Fashion",
    "question": "images/fashion/sneakers.png",
    "answers": [
      {"text": "スニーカー", 'score': 1},
      {"text": "スーニカー", 'score': 0},
      {"text": "スニカー", 'score': 0},
    ],
    "answer": "ネクタイ",
    "meaning": "sneakers",
  },
  {
    "id": "acc6",
    "memo": "Fashion",
    "question": "images/fashion/socks.png",
    "answers": [
      {"text": "ソックス", 'score': 1},
      {"text": "ソクス", 'score': 0},
      {"text": "ソクッス", 'score': 0},
    ],
    "answer": "ソックス",
    "meaning": "socks",
  },
  {
    "id": "acc7",
    "memo": "Fashion",
    "question": "images/fashion/suits.png",
    "answers": [
      {"text": "スーシ", 'score': 0},
      {"text": "スーツ", 'score': 1},
      {"text": "スツツ", 'score': 0},
    ],
    "answer": "スーツ",
    "meaning": "suits",
  },
  {
    "id": "acc8",
    "memo": "Fashion",
    "question": "images/fashion/onepiece.png",
    "answers": [
      {"text": "ワンピース", 'score': 1},
      {"text": "ワンピス", 'score': 0},
      {"text": "ワンピズ", 'score': 0},
    ],
    "answer": "ワンピース",
    "meaning": "onepiece",
  },
  {
    "id": "acc9",
    "memo": "Fashion",
    "question": "images/fashion/sweater.png",
    "answers": [
      {"text": "スエター", 'score': 0},
      {"text": "セーター", 'score': 1},
      {"text": "セター", 'score': 0},
    ],
    "answer": "セーター",
    "meaning": "sweater",
  },
  {
    "id": "acc10",
    "memo": "Fashion",
    "question": "images/fashion/tshirt.png",
    "answers": [
      {"text": "Tシャツ", 'score': 1},
      {"text": "Tショツ", 'score': 0},
      {"text": "Tツャシ", 'score': 0},
    ],
    "answer": "Tシャツ",
    "meaning": "tshirt",
  },
];
